# Generated by Django 5.1 on 2025-10-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePelicula', models.CharField(max_length=255)),
                ('Fecha_Hora', models.DateTimeField()),
                ('Idioma', models.CharField(help_text='Idioma original o de la proyección de la película.', max_length=50)),
            ],
        ),
    ]
