# Generated by Django 5.1 on 2025-10-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Funciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funciones',
            name='Idioma',
            field=models.CharField(max_length=50),
        ),
    ]
